/**
 * The event-type vocabulary from docs/05-authentication-security.md's
 * "Audit logging" section, as a shared const so every call site uses
 * the exact same string rather than retyping it ~20 times across the
 * app.
 */
export const AUDIT_ACTION = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  FAILED_LOGIN: "FAILED_LOGIN",
  SALE_CREATED: "SALE_CREATED",
  SALE_EDITED: "SALE_EDITED",
  SALE_VOIDED: "SALE_VOIDED",
  BUSINESS_DAY_OPENED: "BUSINESS_DAY_OPENED",
  BUSINESS_DAY_CLOSED: "BUSINESS_DAY_CLOSED",
  BUSINESS_DAY_REOPENED: "BUSINESS_DAY_REOPENED",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_EDITED: "PRODUCT_EDITED",
  PRODUCT_DELETED: "PRODUCT_DELETED",
  USER_INVITED: "USER_INVITED",
  USER_INVITE_RESENT: "USER_INVITE_RESENT",
  USER_ONBOARDED: "USER_ONBOARDED",
  USER_DISABLED: "USER_DISABLED",
  USER_ENABLED: "USER_ENABLED",
  USER_NAME_CHANGED: "USER_NAME_CHANGED",
  ROLE_CHANGED: "ROLE_CHANGED",
  PERMISSION_CHANGED: "PERMISSION_CHANGED",
  EXPORT_REQUESTED: "EXPORT_REQUESTED",
  EXPORT_COMPLETED: "EXPORT_COMPLETED",
  SECURITY_SETTING_CHANGED: "SECURITY_SETTING_CHANGED",
  TENANT_SETTING_CHANGED: "TENANT_SETTING_CHANGED",
  BUSINESS_PROFILE_UPDATED: "BUSINESS_PROFILE_UPDATED",
  BUSINESS_HOURS_UPDATED: "BUSINESS_HOURS_UPDATED",
  LOCATION_CREATED: "LOCATION_CREATED",
  LOCATION_UPDATED: "LOCATION_UPDATED",
  LOCATION_DEACTIVATED: "LOCATION_DEACTIVATED",
  LOCATION_REACTIVATED: "LOCATION_REACTIVATED",
  SESSION_REVOKED: "SESSION_REVOKED",
  TEMPORARY_ACCESS_REQUESTED: "TEMPORARY_ACCESS_REQUESTED",
  TEMPORARY_ACCESS_APPROVED: "TEMPORARY_ACCESS_APPROVED",
  TEMPORARY_ACCESS_REJECTED: "TEMPORARY_ACCESS_REJECTED",
  SUBSCRIPTION_CHANGED: "SUBSCRIPTION_CHANGED",
  ADDON_SUBSCRIPTION_CHANGED: "ADDON_SUBSCRIPTION_CHANGED",
  STOCK_MOVEMENT_RECORDED: "STOCK_MOVEMENT_RECORDED",
  STOCK_RECONCILED: "STOCK_RECONCILED",
  IMPERSONATION_STARTED: "IMPERSONATION_STARTED",
  IMPERSONATION_ENDED: "IMPERSONATION_ENDED",
  ACCESS_RESTRICTION_BYPASSED: "ACCESS_RESTRICTION_BYPASSED",
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
